name: 'Terraform Infrastructure GitOps'

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'

jobs:
  terraform:
    name: 'Terraform GitOps'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    # Logowanie bezpośrednio wygenerowanym tokenem z pominięciem MFA i Entra ID
    - name: Azure Login via Access Token
      run: |
        az login --service-principal -u "http://AzureCLI" -p "${{ secrets.AZURE_ACCESS_TOKEN }}" --tenant "common"
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color

    - name: Terraform Apply
      if: github.event_name == 'push'
      run: terraform apply -auto-approve